name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Display current directory
      run: pwd && ls -R
        
    - name: Restore dependencies
      run: dotnet restore BE/BE.csproj
      
    - name: Build
      run: dotnet build BE/BE.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test BE/BE.csproj --no-build --verbosity normal
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: BE-ExploreNowSolution/BE
        file: BE-ExploreNowSolution/BE/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
