# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - be-explore-now

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: https://myexplorenowwebapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cc5ae4d2b74842a8a31507fe96d5f9e7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f135e1eff13149909acb76130b83d1e2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: myexplorenowwebapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cc5ae4d2b74842a8a31507fe96d5f9e7 }}/prn231explorenowapi:${{ github.sha }}
        file: ./Dockerfile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test --no-restore --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'be-explore-now'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4dbe2119868941c9938d46b9753ad464 }}
        images: 'myexplorenowwebapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cc5ae4d2b74842a8a31507fe96d5f9e7 }}/prn231explorenowapi:${{ github.sha }}'
    
    - name: Health check
      run: |
        sleep 120
        response_content=$(curl -sS https://be-explore-now.azurewebsites.net/health)
        response_code=$(curl -sS -o /dev/null -w "%{http_code}" https://be-explore-now.azurewebsites.net/health)
        echo "Response content: $response_content"
        echo "Response code: $response_code"
        if [ $response_code = "200" ]; then
          echo "Health check passed"
        else
          echo "Health check failed with status code $response_code"
          exit 1
        fi
        
    - name: Verify deployment
      run: |
        response=$(curl -sS -o /dev/null -w "%{http_code}" https://be-explore-now.azurewebsites.net/swagger/index.html)
        if [ $response = "200" ]; then
          echo "Deployment successful"
        else
          echo "Deployment failed with status code $response"
          exit 1
        fi
